import type { Theme } from "@/modules/theme/types";

export const githubDarkClassic: Theme = {
  id: "github-dark-classic",
  name: "GitHub Dark Classic",
  description:
    "Neutral charcoal with GitHub Classic colors. Pairs with window transparency and blur.",
  editorTheme: { dark: "github-dark" },
  variants: {
    dark: {
      colors: {
        background: "#0a0a0a",
        foreground: "#d1d5da",
        card: "#0a0a0a",
        cardForeground: "#d1d5da",
        popover: "#1c1c1c",
        popoverForeground: "#e1e4e8",
        primary: "#79b8ff",
        primaryForeground: "#0a0a0a",
        secondary: "#363537",
        secondaryForeground: "#e1e4e8",
        muted: "#1c1c1c",
        mutedForeground: "#959da5",
        accent: "#ffffff18",
        accentForeground: "#e1e4e8",
        destructive: "#f97583",
        border: "#2a2a2a40",
        input: "#444d56",
        ring: "#005cc5",
        sidebar: "#0a0a0a",
        sidebarForeground: "#d1d5da",
        sidebarPrimary: "#79b8ff",
        sidebarPrimaryForeground: "#0a0a0a",
        sidebarAccent: "#ffffff18",
        sidebarAccentForeground: "#e1e4e8",
        sidebarBorder: "#2a2a2a40",
        sidebarRing: "#005cc5",
      },
      terminal: {
        background: "#0a0a0a",
        foreground: "#d1d5da",
        cursor: "#79b8ff",
        cursorAccent: "#0a0a0a",
        selection: "#04428966",
        ansi: [
          "#586069",
          "#ea4a5a",
          "#34d058",
          "#ffea7f",
          "#2188ff",
          "#b392f0",
          "#39c5cf",
          "#d1d5da",
          "#959da5",
          "#f97583",
          "#85e89d",
          "#ffea7f",
          "#79b8ff",
          "#b392f0",
          "#56d4dd",
          "#fafbfc",
        ],
      },
    },
  },
};
